# Generated by Django 6.0.3 on 2026-03-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collection_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
