# Generated by Django 6.0.3 on 2026-04-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_is_active_product_is_deleted_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Rose Gold', 'Rose Gold'), ('Black', 'Black'), ('Blue', 'Blue'), ('White', 'White'), ('Grey', 'Grey'), ('Brown', 'Brown')], default='Silver', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
