# Generated by Django 6.0.3 on 2026-04-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_color_remove_product_color_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='TimeHub', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dial_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='function',
            field=models.CharField(choices=[('Analog', 'Analog'), ('Digital', 'Digital'), ('Chronograph', 'Chronograph'), ('Automatic', 'Automatic')], default='Analog', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Sport', 'Sport'), ('Luxury', 'Luxury')], default='Casual', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='strap_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='strap_material',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
