# Generated by Django 6.0.3 on 2026-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_cancel_reason_order_return_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
