# Generated by Django 6.0.3 on 2026-04-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_scheduled_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reschedule_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
