# Generated by Django 6.0.3 on 2026-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_reschedule_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
