# Generated by Django 6.0.3 on 2026-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_refund_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
