# Generated by Django 6.0.3 on 2026-04-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_refund_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_reschedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_reschedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reschedule_status',
            field=models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='None', max_length=20),
        ),
    ]
