# Generated by Django 6.0.3 on 2026-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_requested_reschedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
