# Generated by Django 6.0.3 on 2026-04-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_reschedule_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Limited Edition', 'Limited Edition'), ('New Arrival', 'New Arrival'), ('Exclusive', 'Exclusive'), ('Luxury', 'Luxury'), ('Premium', 'Premium'), ('Signature Series', 'Signature Series'), ('Best Seller', 'Best Seller')], max_length=50, null=True),
        ),
    ]
