# Generated by Django 6.0.4 on 2026-04-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_coupon_order_coupon_code_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_first_order_only',
            field=models.BooleanField(default=False, help_text="Only for the user's very first order"),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_referral_only',
            field=models.BooleanField(default=False, help_text='Only for users who joined via referral'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_orders_required',
            field=models.PositiveIntegerField(default=0, help_text='Minimum successful orders user must have to use this coupon'),
        ),
    ]
