# Generated by Django 6.0.4 on 2026-04-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coupon_is_first_order_only_coupon_is_referral_only_and_more'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='offers.coupon'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
