# Generated by Django 6.0.4 on 2026-04-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_order_is_paid_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('None', 'None'), ('Requested', 'Requested'), ('Processing', 'Processing'), ('Pickup Scheduled', 'Pickup Scheduled'), ('Returned', 'Returned'), ('Rejected', 'Rejected')], default='None', max_length=20),
        ),
    ]
