# Generated by Django 6.0.4 on 2026-04-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_collection_uuid_alter_order_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
