# Generated by Django 6.0.4 on 2026-05-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_productimage_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
