# Generated by Django 6.0.4 on 2026-05-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_product_seller_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Note from TimeHub curators', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
