# Generated by Django 6.0.4 on 2026-05-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_product_admin_note_product_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dial_color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='dial_color',
        ),
    ]
