# Generated by Django 6.0.4 on 2026-05-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_product_dial_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dial_color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
