# Generated by Django 6.0.4 on 2026-05-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_productimage_order_productvariant_dial_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
