# Generated by Django 6.0.4 on 2026-05-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_comparisonhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total savings from Product/Category offers', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Savings from Coupons/Referrals', max_digits=10),
        ),
    ]
