# Generated by Django 6.0.4 on 2026-06-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_order_offer_discount_alter_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='function',
            field=models.CharField(choices=[('Analog', 'Analog'), ('Digital', 'Digital'), ('Chronograph', 'Chronograph'), ('Automatic', 'Automatic'), ('Smart', 'Smart'), ('Mechanical', 'Mechanical')], default='Analog', max_length=50),
        ),
    ]
