# Generated by Django 6.0.4 on 2026-06-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_productvariant_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='badge',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
