# Generated by Django 6.0.4 on 2026-07-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_productvariant_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='badge',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Limited Edition', 'Limited Edition'), ('New Arrival', 'New Arrival'), ('Exclusive', 'Exclusive'), ('Luxury', 'Luxury'), ('Premium', 'Premium'), ('Signature Series', 'Signature Series'), ('Best Seller', 'Best Seller')], max_length=50, null=True),
        ),
    ]
