# Generated by Django 6.0.4 on 2026-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
