# Generated by Django 6.0.4 on 2026-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_logos/'),
        ),
    ]
