# Generated by Django 6.0.4 on 2026-04-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage value or fixed amount', max_digits=10)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount limit for percentage type', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total number of times this coupon can be used by all users', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_first_order_only', models.BooleanField(default=False, help_text="Only for the user's very first order")),
                ('is_referral_only', models.BooleanField(default=False, help_text='Only for users who joined via referral')),
                ('min_orders_required', models.PositiveIntegerField(default=0, help_text='Minimum successful orders user must have to use this coupon')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
