# Generated by Django 6.0.4 on 2026-04-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_cart_coupon_delete_coupon'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_collection',
            field=models.ForeignKey(blank=True, help_text='Restrict coupon to a specific product collection', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.collection'),
        ),
    ]
