# Generated by Django 6.0.4 on 2026-04-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_coupon_applicable_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='min_orders_required',
        ),
    ]
