# Generated by Django 6.0.4 on 2026-04-29 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_order_is_paid_alter_order_status'),
        ('offers', '0004_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='collection',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_offers', to='core.collection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_percentage',
            field=models.PositiveIntegerField(help_text='Discount in percentage (e.g. 15 for 15%)'),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_percentage',
            field=models.PositiveIntegerField(help_text='Discount in percentage (e.g. 20 for 20%)'),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='valid_from',
            field=models.DateTimeField(),
        ),
    ]
