# Generated by Django 6.0.4 on 2026-04-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_remove_categoryoffer_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_reward', models.DecimalField(decimal_places=2, help_text="Amount credited to referrer's wallet", max_digits=10)),
                ('referee_reward', models.DecimalField(decimal_places=2, help_text="Amount credited to referee's wallet", max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
