# Generated by Django 6.0.4 on 2026-04-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_referraloffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referraloffer',
            name='referee_reward',
        ),
        migrations.AddField(
            model_name='referraloffer',
            name='referee_discount_percent',
            field=models.PositiveIntegerField(default=50, help_text="Discount percentage for referee's first order"),
        ),
        migrations.AddField(
            model_name='referraloffer',
            name='referee_order_reward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount credited to referee after their first order', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referraloffer',
            name='referee_signup_reward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount credited to referee immediately on signup', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referraloffer',
            name='referrer_reward',
            field=models.DecimalField(decimal_places=2, help_text="Amount credited to referrer after referee's first order", max_digits=10),
        ),
    ]
