# Generated by Django 6.0.4 on 2026-05-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_remove_referraloffer_referee_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_items_count',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of items in a cart this coupon can apply to', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit_per_user',
            field=models.PositiveIntegerField(default=1, help_text='How many times a single user can use this coupon'),
        ),
    ]
