# Generated by Django 6.0.4 on 2026-05-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0002_address_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
